### ISSUE TITLE
report one bug during springboot2.7 upgrade to 3.0

### ISSUE THREAD

**Issue by owensmao** [openrewrite/rewrite-migrate-java#207]
![image](https://user-images.githubusercontent.com/7709697/231700908-45d19527-f9de-483e-8af2-c540fbfd656b.png)

Caused by: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.JavaType$FullyQualified.getFullyQualifiedName()" because the return value of "org.openrewrite.java.tree.TypeUtils.asFullyQualified(org.openrewrite.java.tree.JavaType)" is null
        at org.springframework.sbm.java.impl.OpenRewriteMethod.getReturnValue(OpenRewriteMethod.java:167)
        at org.springframework.sbm.boot.common.finder.SpringBeanMethodDeclarationFinder.lambda$apply$1(SpringBeanMethodDeclarationFinder.java:52)
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
        at org.springframework.sbm.boot.common.finder.SpringBeanMethodDeclarationFinder.lambda$apply$2(SpringBeanMethodDeclarationFinder.java:52)

**Comment by knutwannheden** [comment]
@owensmao Thank you for reaching out! Based on the stack trace it looks like this issue should actually be reported to https://github.com/spring-projects-experimental/spring-boot-migrator instead (which is a tool based on OpenRewrite), because `TypeUtils#asFullyQualified(JavaType)` is actually expected to return `null` depending on the argument that is given to it.

I will close this issue for now. Please let us know if we missed something, so that we can reopen and investigate. Thanks!

**Comment by timtebeek** [comment]
> > 
> 
> thank you @knutwannheden . Also i found another issues as bellow Recipes not found: org.openrewrite.java.migrate.jakarta.JavaxServletToJakartaServlet

Do you have the required dependency on rewrite-migrate-java for that one? Instructions for that specific recipe are here:
https://docs.openrewrite.org/reference/recipes/java/migrate/jakarta/javaxservlettojakartaservlet
