### ISSUE TITLE
Missing space before extends/implements using ClassDeclaration#withExtends/withImplements

### ISSUE THREAD

**Issue by MBoegers** [openrewrite/rewrite-migrate-java#226]
## What version of OpenRewrite are you using?
I am using https://github.com/openrewrite/rewrite Branch: main Commit: 9d567a3ba281285d8b20f942921f98e7fcc0ee35

## How are you running OpenRewrite?
I wrote a reproducing test.

## What is the smallest, simplest way to reproduce the problem?
Find a reproducer test here https://gist.github.com/MBoegers/072b1412e9fee01b4728a61e68f44562

## What did you expect to see?
Extending a class with java.util.ArrayList:
**Input:**
```java
class CustomList {}
```
**Result:**
```java
class CustomList extends java.util.ArrayList {}
```

A class implementing java.io.Serializable:
**Input:**
```java
class CustomList {}
```
**Result:**
```java
class CustomList implements java.io.Serializable {}
```

## What did you see instead?
Extending a class with java.util.ArrayList:
```java
class CustomListextends java.util.ArrayList {}
```

A class implementing java.io.Serializable:
```java
class CustomListimplements java.io.Serializable {}
```

## What is the full stack trace of any errors you encountered?
Extending a class with java.util.ArrayList:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

[Unexpected result in "de/example/CustomList.java"
diff --git a/de/example/CustomList.java b/de/example/CustomList.java
index e454a71..a71d73b 100644
--- a/de/example/CustomList.java
+++ b/de/example/CustomList.java
@@ -1,4 +1,4 @@ 
 package de.example;
 
-class CustomList extends java.util.ArrayList {
+class CustomListextends java.util.ArrayList {
 }
\ No newline at end of file
] 
expected: 
  "package de.example;
  
  class CustomList extends java.util.ArrayList {
  }"
 but was: 
  "package de.example;
  
  class CustomListextends java.util.ArrayList {
  }"
org.opentest4j.AssertionFailedError: [Unexpected result in "de/example/CustomList.java"
diff --git a/de/example/CustomList.java b/de/example/CustomList.java
index e454a71..a71d73b 100644
--- a/de/example/CustomList.java
+++ b/de/example/CustomList.java
@@ -1,4 +1,4 @@ 
 package de.example;
 
-class CustomList extends java.util.ArrayList {
+class CustomListextends java.util.ArrayList {
 }
\ No newline at end of file
] 
expected: 
  "package de.example;
  
  class CustomList extends java.util.ArrayList {
  }"
 but was: 
  "package de.example;
  
  class CustomListextends java.util.ArrayList {
  }"
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:446)
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:130)
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:125)
	at app//org.openrewrite.java.tree.WithMissPaddingReproducer$WithExtendsTest.triggerIt(WithMissPaddingReproducer.java:90)
```
A class implementing java.io.Serializable:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

[Unexpected result in "de/example/CustomList.java"
diff --git a/de/example/CustomList.java b/de/example/CustomList.java
index 5be0342..4514ef4 100644
--- a/de/example/CustomList.java
+++ b/de/example/CustomList.java
@@ -1,4 +1,4 @@ 
 package de.example;
 
-class CustomList implements java.io.Serializable {
+class CustomListimplements java.io.Serializable {
 }
\ No newline at end of file
] 
expected: 
  "package de.example;
  
  class CustomList implements java.io.Serializable {
  }"
 but was: 
  "package de.example;
  
  class CustomListimplements java.io.Serializable {
  }"
org.opentest4j.AssertionFailedError: [Unexpected result in "de/example/CustomList.java"
diff --git a/de/example/CustomList.java b/de/example/CustomList.java
index 5be0342..4514ef4 100644
--- a/de/example/CustomList.java
+++ b/de/example/CustomList.java
@@ -1,4 +1,4 @@ 
 package de.example;
 
-class CustomList implements java.io.Serializable {
+class CustomListimplements java.io.Serializable {
 }
\ No newline at end of file
] 
expected: 
  "package de.example;
  
  class CustomList implements java.io.Serializable {
  }"
 but was: 
  "package de.example;
  
  class CustomListimplements java.io.Serializable {
  }"
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:446)
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:130)
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:125)
	at app//org.openrewrite.java.tree.WithMissPaddingReproducer$WithImplementsTest.triggerIt(WithMissPaddingReproducer.java:119)
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
Maybe after my current PR.

**Comment by timtebeek** [comment]
I'm inclined to think this is more likely an issue with openrewrite/rewrite rather than openrewrite/rewrite-migrate-java; what made you open the issue here @MBoegers ?

**Comment by MBoegers** [comment]
Yes you are right! I just discovered it while developing within openrewrite/rewrite-migrate-java.
I can reopen one in openrewrite/rewrite
________________________________
Von: Tim te Beek ***@***.***>
Gesendet: Friday, June 2, 2023 2:17:48 PM
An: openrewrite/rewrite-migrate-java ***@***.***>
Cc: Merlin Bögershausen ***@***.***>; Mention ***@***.***>
Betreff: Re: [openrewrite/rewrite-migrate-java] Missing space before extends/implements using ClassDeclaration#withExtends/withImplements (Issue #226)


I'm inclined to think this is more likely an issue with openrewrite/rewrite rather than openrewrite/rewrite-migrate-java; what made you open the issue here @MBoegers<https://github.com/MBoegers> ?
