### ISSUE TITLE
Issue with `StringFormatted` recipe

### ISSUE THREAD

**Issue by mankoffs** [openrewrite/rewrite-migrate-java#598]
## What version of OpenRewrite are you using?

I am using

- Maven/Gradle plugin 5.43.4
- rewrite-migrate-java 2.28.0

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a multi-module project.
```java
mvn clean org.openrewrite.maven:rewrite-maven-plugin:5.43.4:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:RELEASE -Drewrite.activeRecipes=org.openrewrite.java.migrate.lang.StringFormatted
```

## What is the smallest, simplest way to reproduce the problem?

```java
package com.example.app;                          
import lombok.Data;                               
                                                  
@Data                                             
class Person {                                    
    Long age;                                     
}                                                 
class A {                                         
    public void m(Person person) {                
        var i = person.getAge();                  
        String str = String.format("age #%d", i); 
    }                                             
}
```

## What did you expect to see?

```java
package com.example.app;                    
import lombok.Data;                         
                                            
@Data                                       
class Person {                              
    Long age;                               
}                                           
class A {                                   
    public void m(Person person) {          
        var i = person.getAge();            
        String str = "age #%d".formatted(i);
    }                                       
}                                      
```

## What did you see instead? (Recipe was expected to make a change but made no changes)

```java
package com.example.app;                          
import lombok.Data;                               
                                                  
@Data                                             
class Person {                                    
    Long age;                                     
}                                                 
class A {                                         
    public void m(Person person) {                
        var i = person.getAge();                  
        String str = String.format("age #%d", i); 
    }                                             
}                                    
```

## What is the full stack trace of any errors you encountered?

```
java.lang.AssertionError: Recipe was expected to make a change but made no changes.
	at org.openrewrite.test.LargeSourceSetCheckingExpectedCycles.afterCycle(LargeSourceSetCheckingExpectedCycles.java:119)
	at org.openrewrite.RecipeScheduler.runRecipeCycles(RecipeScheduler.java:98)
	at org.openrewrite.RecipeScheduler.scheduleRun(RecipeScheduler.java:41)
	at org.openrewrite.Recipe.run(Recipe.java:376)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:376)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:132)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:127)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

## Additional information

The recipe works as expected if:

- `var` is replaced with Long
or
- if add an explicit getter for the `Person` class (public Long getAge() {return age;}})

**Comment by timtebeek** [comment]
Hi @mankoffs ; The issues you're seeing here are most likely related to the use of Lombok; we've made improvements there recently, but for now it's still needs to be enabled explicitly:
 - https://github.com/openrewrite/rewrite/pull/4602

Once that's further along you'll see improvements here as well. I don't think there's anything specific to this recipe to fix right now; it'll just start to make the expected changes when Lombok support fully lands.
