### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by Jonpez2** [openrewrite/rewrite-migrate-java#65]
I’m not sure if this belongs in this repo or the main openrewrite repo but… what are the plans for support of java 17 record syntax and all the upcoming pattern matching features please?

Thank you - and thanks for the amazing tool!

**Comment by jkschneider** [comment]
Our biggest technical hurdle is the constraints Jigsaw is placing on us. We either need to map from ECJ or find a way around the inability to open internal modules like the compiler in Java 17.

**Comment by Jonpez2** [comment]
Do you mean so that openrewrite can run under jdk17? That’s already working for me - the —add-opens lines that you so helpfully document made this just work. 
I actually meant parsing the jdk17 syntax, understanding records and so forth. 
Let me know if I’m misunderstanding your answer please - I don’t mean to waste your time! And if you want me to specifically give examples of what doesn’t work for me that’s obviously fair enough.

**Comment by Jonpez2** [comment]
Here is a specific usecase that's breaking me:

The class file below produces the stack trace included at the bottom.

======
package rewrite;

import com.gs.ctl.eventgraph.IdentityRef;

public class C {
    // Works
    private class RawEdgeC {
        IdentityRef idr;
    }

    // Works
    private record RawEdgeI(int i) {

    }

    // Works
    private record RawEdgeO(Object i) {

    }

    // Bang
    private record RawEdgeBoom(IdentityRef id) {
    }
}
=====

org.openrewrite.java.JavaParsingException: Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = /home/coder/IdeaProjects/ctl-core/development-tools/rewrite/smoke-test-class.java)
JCClassDecl(name = C, line = 6)
JCClassDecl(name = RawEdgeBoom, line = 23)
--- END PATH ---

	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1483)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1489)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1598)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1580)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:461)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1460)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1489)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1598)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1580)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:461)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1460)
	at org.openrewrite.java.Java11ParserVisitor.convertAll(Java11ParserVisitor.java:1513)
	at org.openrewrite.java.Java11ParserVisitor.visitCompilationUnit(Java11ParserVisitor.java:503)
	at org.openrewrite.java.Java11ParserVisitor.visitCompilationUnit(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11Parser.lambda$parseInputs$0(Java11Parser.java:175)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.openrewrite.java.Java11Parser.parseInputs(Java11Parser.java:197)
	at org.openrewrite.Parser.parse(Parser.java:39)
	at rewrite.MigrateToFluentLoggerRecipe.main(MigrateToFluentLoggerRecipe.java:168)
Caused by: java.lang.IndexOutOfBoundsException: Illegal start index
	at java.base/java.util.regex.Matcher.find(Matcher.java:770)
	at org.openrewrite.java.Java11ParserVisitor.lambda$visitVariables$28(Java11ParserVisitor.java:1369)
	at org.openrewrite.java.Java11ParserVisitor.visitVariables(Java11ParserVisitor.java:1376)
	at org.openrewrite.java.Java11ParserVisitor.visitVariable(Java11ParserVisitor.java:1324)
	at org.openrewrite.java.Java11ParserVisitor.visitVariable(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1045)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1460)
	... 33 more
org.openrewrite.java.JavaParsingException: Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = /home/coder/IdeaProjects/ctl-core/development-tools/rewrite/smoke-test-class.java)
JCClassDecl(name = C, line = 6)
--- END PATH ---

	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1483)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1489)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1598)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1580)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:461)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1460)
	at org.openrewrite.java.Java11ParserVisitor.convertAll(Java11ParserVisitor.java:1513)
	at org.openrewrite.java.Java11ParserVisitor.visitCompilationUnit(Java11ParserVisitor.java:503)
	at org.openrewrite.java.Java11ParserVisitor.visitCompilationUnit(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11Parser.lambda$parseInputs$0(Java11Parser.java:175)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.openrewrite.java.Java11Parser.parseInputs(Java11Parser.java:197)
	at org.openrewrite.Parser.parse(Parser.java:39)
	at rewrite.MigrateToFluentLoggerRecipe.main(MigrateToFluentLoggerRecipe.java:168)
Caused by: java.lang.IndexOutOfBoundsException: Illegal start index
	at java.base/java.util.regex.Matcher.find(Matcher.java:770)
	at org.openrewrite.java.Java11ParserVisitor.lambda$visitVariables$28(Java11ParserVisitor.java:1369)
	at org.openrewrite.java.Java11ParserVisitor.visitVariables(Java11ParserVisitor.java:1376)
	at org.openrewrite.java.Java11ParserVisitor.visitVariable(Java11ParserVisitor.java:1324)
	at org.openrewrite.java.Java11ParserVisitor.visitVariable(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1045)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1460)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1489)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1598)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1580)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:461)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1460)
	... 25 more
org.openrewrite.java.JavaParsingException: Failed to convert for the following cursor stack:--- BEGIN PATH ---
JCCompilationUnit(sourceFile = /home/coder/IdeaProjects/ctl-core/development-tools/rewrite/smoke-test-class.java)
--- END PATH ---

	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1483)
	at org.openrewrite.java.Java11ParserVisitor.convertAll(Java11ParserVisitor.java:1513)
	at org.openrewrite.java.Java11ParserVisitor.visitCompilationUnit(Java11ParserVisitor.java:503)
	at org.openrewrite.java.Java11ParserVisitor.visitCompilationUnit(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11Parser.lambda$parseInputs$0(Java11Parser.java:175)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.openrewrite.java.Java11Parser.parseInputs(Java11Parser.java:197)
	at org.openrewrite.Parser.parse(Parser.java:39)
	at rewrite.MigrateToFluentLoggerRecipe.main(MigrateToFluentLoggerRecipe.java:168)
Caused by: java.lang.IndexOutOfBoundsException: Illegal start index
	at java.base/java.util.regex.Matcher.find(Matcher.java:770)
	at org.openrewrite.java.Java11ParserVisitor.lambda$visitVariables$28(Java11ParserVisitor.java:1369)
	at org.openrewrite.java.Java11ParserVisitor.visitVariables(Java11ParserVisitor.java:1376)
	at org.openrewrite.java.Java11ParserVisitor.visitVariable(Java11ParserVisitor.java:1324)
	at org.openrewrite.java.Java11ParserVisitor.visitVariable(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1045)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1460)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1489)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1598)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1580)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:461)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1460)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1489)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1598)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1580)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:461)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1460)
	... 17 more
java.lang.IndexOutOfBoundsException: Illegal start index
	at java.base/java.util.regex.Matcher.find(Matcher.java:770)
	at org.openrewrite.java.Java11ParserVisitor.lambda$visitVariables$28(Java11ParserVisitor.java:1369)
	at org.openrewrite.java.Java11ParserVisitor.visitVariables(Java11ParserVisitor.java:1376)
	at org.openrewrite.java.Java11ParserVisitor.visitVariable(Java11ParserVisitor.java:1324)
	at org.openrewrite.java.Java11ParserVisitor.visitVariable(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1045)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1460)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1489)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1598)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1580)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:461)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1460)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1489)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1598)
	at org.openrewrite.java.Java11ParserVisitor.convertStatements(Java11ParserVisitor.java:1580)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:461)
	at org.openrewrite.java.Java11ParserVisitor.visitClass(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1460)
	at org.openrewrite.java.Java11ParserVisitor.convertAll(Java11ParserVisitor.java:1513)
	at org.openrewrite.java.Java11ParserVisitor.visitCompilationUnit(Java11ParserVisitor.java:503)
	at org.openrewrite.java.Java11ParserVisitor.visitCompilationUnit(Java11ParserVisitor.java:69)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at org.openrewrite.java.Java11Parser.lambda$parseInputs$0(Java11Parser.java:175)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.openrewrite.java.Java11Parser.parseInputs(Java11Parser.java:197)
	at org.openrewrite.Parser.parse(Parser.java:39)
